### ISSUE TITLE
Add clear connection error report if UTA does not connect

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [openvar/variantValidator#164]
Current message looks something like this if the wrong schema is specified for example
```python
Traceback (most recent call last):
  File "/home/sdenil/software/anaconda3/lib/python3.7/site-packages/vvhgvs/dataproviders/uta.py", line 477, in __del__
    self.close()
  File "/home/sdenil/software/anaconda3/lib/python3.7/site-packages/vvhgvs/dataproviders/uta.py", line 481, in close
    self._pool.closeall()
AttributeError: 'UTA_postgresql' object has no attribute '_pool'
```
Can this be improved?

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantValidator/issues/149
