### ISSUE TITLE
chr16-8619836-G-T causing issues with reverse mapping back to genome

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [openvar/variantValidator#295]
**Describe the bug**
Variant chr16-8619836-G-T is causing a t_back to g mapping that causes the formation of a delins variant. This does not appear to be a gap-gene

**To Reproduce**
Run VV validator function chr16-8619836-G-T GRCh37

**Expected behavior**
```python
NM_001290097.2:c.-206A=
NM_001290095.1:c.172C>A
NM_001146336.1:c.310G>A
NR_110736.2:n.15-89C>A
ERROR: <class 'vvhgvs.exceptions.HGVSInvalidVariantError'> base start position must be <= end position
CRITICAL: <class 'vvhgvs.exceptions.HGVSInvalidVariantError'> base start position must be <= end position
Traceback (most recent call last):
  File "/Users/pjf9/PycharmProjects/variantValidator/VariantValidator/modules/vvMixinCore.py", line 484, in validate
    toskip = mappers.transcripts_to_gene(my_variant, self, select_transcripts_dict_plus_version)
  File "/Users/pjf9/PycharmProjects/variantValidator/VariantValidator/modules/mappers.py", line 283, in transcripts_to_gene
    formatted_variant = str(validator.myevm_g_to_t(variant.evm, to_g, tx_ac))
  File "/Users/pjf9/PycharmProjects/variantValidator/VariantValidator/modules/vvMixinConverters.py", line 948, in myevm_g_to_t
    hgvs_t = evm.g_to_t(hgvs_genomic, alt_ac)
  File "/Users/pjf9/anaconda3/envs/vvenv/lib/python3.6/site-packages/vvhgvs/assemblymapper.py", line 90, in g_to_t
    var_out = super(AssemblyMapper, self).g_to_t(var_g, tx_ac, alt_aln_method=self.alt_aln_method)
  File "/Users/pjf9/anaconda3/envs/vvenv/lib/python3.6/site-packages/vvhgvs/variantmapper.py", line 101, in g_to_t
    self._validator.validate(var_g)
  File "/Users/pjf9/anaconda3/envs/vvenv/lib/python3.6/site-packages/vvhgvs/validator.py", line 33, in validate
    return self._ivr.validate(var, strict) and self._evr.validate(var, strict)
  File "/Users/pjf9/anaconda3/envs/vvenv/lib/python3.6/site-packages/vvhgvs/validator.py", line 53, in validate
    raise HGVSInvalidVariantError(msg)
vvhgvs.exceptions.HGVSInvalidVariantError: base start position must be <= end position
```

**Comment by PeteCausey-Freeman** [comment]
The issue is with a non-coding transcript
mapping is

Expected example
```NM_001146336.1:c.310G>A
NC_000016.9:g.8619836G>T```

Incorrect example
```NR_110736.2:n.15-89C>A
NC_000016.9:g.8619837_8619836delinsT```

**Comment by PeteCausey-Freeman** [comment]
The alignment for this transcript is a total mess
```json
       {
            "coding_end": null,
            "coding_start": null,
            "description": "Homo sapiens transmembrane protein 114 (TMEM114), transcript variant 5, non-coding RNA",
            "genomic_spans": {
                "NC_000016.10": {
                    "end_position": 8589838,
                    "exon_structure": [
                        {
                            "cigar": "220=",
                            "exon_number": 4,
                            "genomic_end": 8589838,
                            "genomic_start": 8589619,
                            "transcript_end": 220,
                            "transcript_start": 1
                        },
                        {
                            "cigar": "81=",
                            "exon_number": 3,
                            "genomic_end": 8589293,
                            "genomic_start": 8589213,
                            "transcript_end": 301,
                            "transcript_start": 221
                        },
                        {
                            "cigar": "93=",
                            "exon_number": 2,
                            "genomic_end": 8552207,
                            "genomic_start": 8552115,
                            "transcript_end": 394,
                            "transcript_start": 302
                        },
                        {
                            "cigar": "127=",
                            "exon_number": 1,
                            "genomic_end": 8526678,
                            "genomic_start": 8526552,
                            "transcript_end": 521,
                            "transcript_start": 395
                        }
                    ],
                    "orientation": -1,
                    "start_position": 8526552,
                    "total_exons": 4
                },
                "NC_000016.9": {
                    "end_position": 8621970,
                    "exon_structure": [
                        {
                            "cigar": "7=1X6=",
                            "exon_number": 4,
                            "genomic_end": 8621970,
                            "genomic_start": 8621957,
                            "transcript_end": 14,
                            "transcript_start": 1
                        },
                        {
                            "cigar": "16D4=1X2=2X6=1X2=1X2=",
                            "exon_number": 3,
                            "genomic_end": 8619747,
                            "genomic_start": 8619727,
                            "transcript_end": 51,
                            "transcript_start": 15
                        },
                        {
                            "cigar": "161D93=",
                            "exon_number": 2,
                            "genomic_end": 8602209,
                            "genomic_start": 8602117,
                            "transcript_end": 305,
                            "transcript_start": 52
                        },
                        {
                            "cigar": "127=",
                            "exon_number": 1,
                            "genomic_end": 8576680,
                            "genomic_start": 8576554,
                            "transcript_end": 432,
                            "transcript_start": 306
                        }
                    ],
                    "orientation": -1,
                    "start_position": 8576554,
                    "total_exons": 4
                }
            },
            "length": 521,
            "reference": "NR_110736.2",
            "translation": null
        },
```
