### ISSUE TITLE
pytest error

### ISSUE THREAD

**Issue by yebean-k** [openvar/variantValidator#353]
hi,

I finished all the installation and config file creation, and then I was trying to pytest.
But this error keeps appearing.
Can you explain why?

1. ERROR:  relation "full_tx_aln_w_nq_cigar_mv" does not exist at character 199
![image](https://user-images.githubusercontent.com/85978192/156957094-feb85e8c-d182-4ba0-9d42-b044535b7bb7.png)

2. AttributeError: 'UTA_postgresql' object has no attribute '_pool'
ex)
Exception ignored in: <bound method UTA_postgresql.__del__ of <vvhgvs.dataproviders.uta.UTA_postgresql object at 0x111899128>>
Traceback (most recent call last):
  File "/Users/kim-yeabean/opt/anaconda3/envs/vvenv/lib/python3.6/site-packages/vvhgvs/dataproviders/uta.py", line 515, in __del__
    self.close()
  File "/Users/kim-yeabean/opt/anaconda3/envs/vvenv/lib/python3.6/site-packages/vvhgvs/dataproviders/uta.py", line 519, in close
    self._pool.closeall()
AttributeError: 'UTA_postgresql' object has no attribute '_pool'

**Comment by yebean-k** [comment]
This issue has been resolved!

It was a problem because I did not install UTA.

However, another problem arose.

I'm getting a TypeError and I don't know why.

Help me..
<img width="984" alt="image" src="https://user-images.githubusercontent.com/85978192/156974247-d22eef42-64ba-486d-a916-068eed15ddc6.png">
