### ISSUE TITLE
SequenceVariant does not support indexing

### ISSUE THREAD

**Issue by sbenny1230** [openvar/variantValidator#387]
Issue with indexing of object when calling transcript_to_gene method of mappers. 

**To Reproduce**
```python
import json
import VariantValidator
vval = VariantValidator.Validator()
variant = 'ENST00000371817.8:c.5071A>T' # variant 2
genome_build = 'GRCh37'
select_transcripts = 'all'
transcript_set = 'ensembl'
validate = vval.validate(variant, genome_build, select_transcripts, transcript_set)
validation = validate.format_as_dict(with_meta=True)
print(json.dumps(validation, sort_keys=True, indent=4, separators=(',', ': ')))
```

**Output**
```
ERROR: <class 'TypeError'> 'SequenceVariant' object does not support indexing
CRITICAL: <class 'TypeError'> 'SequenceVariant' object does not support indexing
Traceback (most recent call last):
  File "/mnt/c/Users/suzmi/Documents/GitHub/variantValidator/VariantValidator/modules/vvMixinCore.py", line 718, in validate
    toskip = mappers.transcripts_to_gene(my_variant, self, select_transcripts_dict_plus_version)
  File "/mnt/c/Users/suzmi/Documents/GitHub/variantValidator/VariantValidator/modules/mappers.py", line 316, in transcripts_to_gene
    print(obj[0])
TypeError: 'SequenceVariant' object does not support indexing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "temp.py", line 9, in <module>
    validate = vval.validate(variant, genome_build, select_transcripts, transcript_set)
  File "/mnt/c/Users/suzmi/Documents/GitHub/variantValidator/VariantValidator/modules/vvMixinCore.py", line 1398, in validate
    raise fn.VariantValidatorError('Validation error')
VariantValidator.modules.utils.VariantValidatorError: Validation error
```

**Comment by sbenny1230** [comment]
Hey,

Branch to clone is [vv_ensembl_develop](https://github.com/openvar/variantValidator/tree/vv_ensembl_develop)

**Comment by Peter-J-Freeman** [comment]
Ok @sbenny1230 
Oddly I got different issues to you. I have applied fixes for the bug I got based on the python code above you provided. Had to make a small ammendment

```python
import json
import VariantValidator
vval = VariantValidator.Validator()
variant = 'ENST00000371817.8:c.5071A>T' # variant 2
genome_build = 'GRCh38'
select_transcripts = 'all'
transcript_set = 'ensembl'
validate = vval.validate(variant, genome_build, select_transcripts, transcript_set)
validation = validate.format_as_dict(with_meta=True)
print(json.dumps(validation, sort_keys=True, indent=4, separators=(',', ': ')))
```

The output is not 

```json
{
    "flag": "warning",
    "metadata": {
        "variantvalidator_hgvs_version": "2.0.2.dev1+g6ecbf8e",
        "variantvalidator_version": "2.1.1.dev2+g294fd63",
        "vvdb_version": "vvdb_2022_04",
        "vvseqrepo_db": "VV_SR_2022_02/master",
        "vvta_version": "vvta_2022_02"
    },
    "validation_warning_1": {
        "alt_genomic_loci": [],
        "annotations": {},
        "gene_ids": {},
        "gene_symbol": "",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "",
            "lrg_tlr": "",
            "slr": "",
            "tlr": ""
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "",
        "primary_assembly_loci": {},
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "selected_assembly": "GRCh37",
        "submitted_variant": "ENST00000371817.8:c.5071A>T",
        "transcript_description": "COL5A1-201",
        "validation_warnings": [
            "Required information for ENST00000371817.8 is missing from the Universal Transcript Archive",
            "Query gene2transcripts with search term ENST00000371817 for available transcripts"
        ],
        "variant_exonic_positions": null
    }
}
```

You will see my commit below. See if you get the same if you fetch and checkout my branch. What this is telling me is that transcript ENST00000371817.8 is not present in the VVTA database. I will check this. and get back to you.

**Comment by sbenny1230** [comment]
Hi @Peter-J-Freeman,

So fetched your branch and tried your script and it's giving me a different error, different to the one I got before too!


```
{
    "flag": "warning",
    "metadata": {
        "variantvalidator_hgvs_version": "2.0.2.dev1+g6ecbf8e",
        "variantvalidator_version": "1.0.5.dev273+g7d58e7e.d20220617",
        "vvdb_version": "vvdb_2022_04",
        "vvseqrepo_db": "VV_SR_2022_02/master",
        "vvta_version": "vvta_2022_02"
    },
    "validation_warning_1": {
        "alt_genomic_loci": [],
        "annotations": {},
        "gene_ids": {},
        "gene_symbol": "",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "",
            "lrg_tlr": "",
            "slr": "",
            "tlr": ""
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "",
        "primary_assembly_loci": {},
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "selected_assembly": "GRCh38",
        "submitted_variant": "ENST00000371817.8:c.5071A>T",
        "transcript_description": "",
        "validation_warnings": [
            "Cannot retrieve data from Ensembl REST for record ENST00000371817.8. Please try again later and if the problem persists contact admin."
        ],
        "variant_exonic_positions": null
    }
}
```

I'll take a look and see what went wrong.

**Comment by Peter-J-Freeman** [comment]
No worries. I'm checking to see if the transcript is in VVTA

**Comment by Peter-J-Freeman** [comment]
OK it looks like the transcript IS in VVTA

![image](https://user-images.githubusercontent.com/26568889/177747380-403af0b2-fc89-4113-baa8-05be25b8a7b7.png)

I accidentally added a bad return statement. Re pull my branch and re-run and hopefully you get

```json
{
    "ENST00000371817.8:c.5071A>T": {
        "alt_genomic_loci": [],
        "annotations": {
            "chromosome": "9",
            "db_xref": {
                "CCDS": null,
                "ensemblgene": "ENSG00000130635",
                "hgnc": "HGNC:2209",
                "ncbigene": null,
                "select": "MANE"
            },
            "ensembl_select": true,
            "mane_plus_clinical": false,
            "mane_select": true,
            "map": "9q34.3",
            "note": "collagen type V alpha 1 chain",
            "refseq_select": false,
            "variant": "201"
        },
        "gene_ids": {
            "ccds_ids": [
                "CCDS6982",
                "CCDS75932"
            ],
            "ensembl_gene_id": "ENSG00000130635",
            "entrez_gene_id": "1289",
            "hgnc_id": "HGNC:2209",
            "omim_id": [
                "120215"
            ],
            "ucsc_id": "uc004cfe.5"
        },
        "gene_symbol": "COL5A1",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "",
            "lrg_tlr": "",
            "slr": "ENSP00000360882.3:p.(R1691*)",
            "tlr": "ENSP00000360882.3:p.(Arg1691Ter)"
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "ENST00000371817.8:c.5071A>T",
        "primary_assembly_loci": {},
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "selected_assembly": "GRCh38",
        "submitted_variant": "ENST00000371817.8:c.5071A>T",
        "transcript_description": "COL5A1-201",
        "validation_warnings": [
            "Cannot retrieve data from Ensembl REST for record ENST00000371817.8. Please try again later and if the problem persists contact admin.",
            "RefSeqGene record not available",
            "ENST00000371817.8:c.5071A>T cannot be mapped directly to genome build GRCh38",
            "See alternative genomic loci or alternative genome builds for aligned genomic positions"
        ],
        "variant_exonic_positions": null
    },
    "flag": "gene_variant",
    "metadata": {
        "variantvalidator_hgvs_version": "2.0.2.dev1+g6ecbf8e",
        "variantvalidator_version": "2.1.1.dev2+g294fd63",
        "vvdb_version": "vvdb_2022_04",
        "vvseqrepo_db": "VV_SR_2022_02/master",
        "vvta_version": "vvta_2022_02"
    }
}
```

Things are beginning to work!!!!! Try find out why we are seeing 

```json
            "ENST00000371817.8:c.5071A>T cannot be mapped directly to genome build GRCh38",
            "See alternative genomic loci or alternative genome builds for aligned genomic positions"
```

so your next job is to find out where the message `Required information for ENST00000371817.8 is missing from the Universal Transcript Archive` is coming from.

**Comment by Peter-J-Freeman** [comment]
Basically it looks like for this variant, almost everything is working except genome mapping. Wonder why?

**Comment by sbenny1230** [comment]
@Peter-J-Freeman Just tested and getting the same result as you now, yay! I'll take a look at the new errors

**Comment by Peter-J-Freeman** [comment]
remember to also look at the commits to see what I changed. Helps you understand the code

**Comment by sbenny1230** [comment]
Had a look and the `Required information for ENST00000371817.8 is missing from the Universal Transcript Archive` seems to be because of the transcripts_to_gene() method from mappers.py. It basically fails when its querying the mysql database transcript_info with the refSeqID as ENST00000371817.8.

I'm still trying to understand exactly what transcripts_to_gene() does but by getting rid of the automapping of ensembl references to a refseq one, this part fails. 

I'm going to test out a few things once I've figured out exactly how the methods are all joining together.

**Comment by Peter-J-Freeman** [comment]
Ok, good stuff. 

The transcript is in the database

transcript_info
```
285572	ENST00000371817.8	COL5A1-201	{"db_xref": {"ensemblgene": "ENSG00000130635", "ncbigene": null, "CCDS": null, "select": "MANE", "hgnc": "HGNC:2209"}, "chromosome": "9", "map": "9q34.3", "note": "collagen type V alpha 1 chain", "variant": "201", "mane_select": true, "mane_plus_clinical": false, "ensembl_select": true, "refseq_select": false}	ENST00000371817.8	COL5A1	unassigned	2021-04-14 12:03:33
```

*Note, the update script needs to be adjusted to make sure the timestamp is reset!*

Here is the stable gene ID
```
14644	COL5A1	HGNC:2209	1289	ENSG00000130635	uc004cfe.5	["120215"]	OTTHUMG00000020891	["CCDS6982", "CCDS75932"]
```

Let me know if you get stuck and push code up for me to look at with the run-script as you have above.

**Comment by sbenny1230** [comment]
Hi,

So just an update, the code seems to be working now when the build is GRCh38 but still getting the same error when the build is GRCh37.

I'm just going to clean up some bits and then merge the changes into vv_ensembl for reviewing

**Comment by sbenny1230** [comment]
So I've been going through each of the test variants and for some, GRCh37 doesn't work and for others GRCh38 doesn't work. 

Example 1:
```python
import json
import VariantValidator

vval = VariantValidator.Validator()
variant = 'ENST00000225964.10:c.589-1GG>G'
genome_build = 'GRCh37'
select_transcripts = 'all'
transcript_set = 'ensembl'
validate = vval.validate(variant, genome_build,
                         select_transcripts, transcript_set)
validation = validate.format_as_dict(with_meta=True)
print(json.dumps(validation, sort_keys=True, indent=4, separators=(',', ': ')))
```

```
{
    "ENST00000225964.10:c.590del": {
        "alt_genomic_loci": [],
        "annotations": {
            "chromosome": "17",
            "db_xref": {
                "CCDS": null,
                "ensemblgene": "ENSG00000108821",
                "hgnc": "HGNC:2197",
                "ncbigene": null,
                "select": "MANE"
            },
            "ensembl_select": true,
            "mane_plus_clinical": false,
            "mane_select": true,
            "map": "17q21.33",
            "note": "collagen type I alpha 1 chain",
            "refseq_select": false,
            "variant": "201"
        },
        "gene_ids": {
            "ccds_ids": [
                "CCDS11561"
            ],
            "ensembl_gene_id": "ENSG00000108821",
            "entrez_gene_id": "1277",
            "hgnc_id": "HGNC:2197",
            "omim_id": [
                "120150"
            ],
            "ucsc_id": "uc002iqm.4"
        },
        "gene_symbol": "COL1A1",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "",
            "lrg_tlr": "",
            "slr": "ENSP00000225964.6:p.(G197Vfs*68)",
            "tlr": "ENSP00000225964.6:p.(Gly197ValfsTer68)"
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "ENST00000225964.10:c.590del",
        "primary_assembly_loci": {
            "grch37": {
                "hgvs_genomic_description": "NC_000017.10:g.48275364del",
                "vcf": {
                    "alt": "A",
                    "chr": "17",
                    "pos": "48275361",
                    "ref": "AC"
                }
            },
            "grch38": {
                "hgvs_genomic_description": "NC_000017.11:g.50198003del",
                "vcf": {
                    "alt": "A",
                    "chr": "17",
                    "pos": "50198000",
                    "ref": "AC"
                }
            },
            "hg19": {
                "hgvs_genomic_description": "NC_000017.10:g.48275364del",
                "vcf": {
                    "alt": "A",
                    "chr": "chr17",
                    "pos": "48275361",
                    "ref": "AC"
                }
            },
            "hg38": {
                "hgvs_genomic_description": "NC_000017.11:g.50198003del",
                "vcf": {
                    "alt": "A",
                    "chr": "chr17",
                    "pos": "50198000",
                    "ref": "AC"
                }
            }
        },
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "selected_assembly": "GRCh37",
        "submitted_variant": "ENST00000225964.10:c.589-1GG>G",
        "transcript_description": "COL1A1-201",
        "validation_warnings": [
            "ENST00000225964.10:c.589-1GG>G automapped to ENST00000225964.10:c.589-1_589delGGinsG",
            "Removing redundant reference bases from variant description",
            "ENST00000225964.10:c.590delG cannot be mapped directly to genome build GRCh37",
            "See alternative genomic loci or alternative genome builds for aligned genomic positions"
        ],
        "variant_exonic_positions": null
    },
    "flag": "gene_variant",
    "metadata": {
        "variantvalidator_hgvs_version": "2.0.2.dev1+g6ecbf8e",
        "variantvalidator_version": "1.0.5.dev273+g7d58e7e.d20220617",
        "vvdb_version": "vvdb_2022_04",
        "vvseqrepo_db": "VV_SR_2022_02/master",
        "vvta_version": "vvta_2022_02"
    }
}
```

Example 2: 
```python
import json
import logging
import VariantValidator

vval = VariantValidator.Validator()
variant = 'NC_000013.10:g.32929387T>C'
genome_build = 'GRCh38'
select_transcripts = 'all'
transcript_set = 'ensembl'
validate = vval.validate(variant, genome_build,
                         select_transcripts, transcript_set)
validation = validate.format_as_dict(with_meta=True)
print(json.dumps(validation, sort_keys=True, indent=4, separators=(',', ': ')))
```

```
{
    "ENST00000380152.3:c.7397T>C": {
        "alt_genomic_loci": [],
        "annotations": {
            "chromosome": "13",
            "db_xref": {
                "CCDS": null,
                "ensemblgene": "ENSG00000139618",
                "hgnc": "1101",
                "ncbigene": null,
                "select": false
            },
            "ensembl_select": false,
            "mane_plus_clinical": false,
            "mane_select": false,
            "map": "13q13.1",
            "note": "BRCA2 DNA repair associated",
            "refseq_select": false,
            "variant": "001"
        },
        "gene_ids": {
            "ccds_ids": [
                "CCDS9344"
            ],
            "ensembl_gene_id": "ENSG00000139618",
            "entrez_gene_id": "675",
            "hgnc_id": "HGNC:1101",
            "omim_id": [
                "600185"
            ],
            "ucsc_id": "uc001uub.2"
        },
        "gene_symbol": "BRCA2",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "",
            "lrg_tlr": "",
            "slr": "ENSP00000369497.3:p.(V2466A)",
            "tlr": "ENSP00000369497.3:p.(Val2466Ala)"
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "ENST00000380152.3:c.7397T>C",
        "primary_assembly_loci": {
            "grch37": {
                "hgvs_genomic_description": "NC_000013.10:g.32929387T>C",
                "vcf": {
                    "alt": "C",
                    "chr": "13",
                    "pos": "32929387",
                    "ref": "T"
                }
            },
            "grch38": {
                "hgvs_genomic_description": "NC_000013.11:g.32355250T>C",
                "vcf": {
                    "alt": "C",
                    "chr": "13",
                    "pos": "32355250",
                    "ref": "T"
                }
            },
            "hg19": {
                "hgvs_genomic_description": "NC_000013.10:g.32929387T>C",
                "vcf": {
                    "alt": "C",
                    "chr": "chr13",
                    "pos": "32929387",
                    "ref": "T"
                }
            },
            "hg38": {
                "hgvs_genomic_description": "NC_000013.11:g.32355250T>C",
                "vcf": {
                    "alt": "C",
                    "chr": "chr13",
                    "pos": "32355250",
                    "ref": "T"
                }
            }
        },
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "selected_assembly": "GRCh38",
        "submitted_variant": "NC_000013.10:g.32929387T>C",
        "transcript_description": "BRCA2-001",
        "validation_warnings": [
            "A more recent version of the selected reference sequence ENST00000380152.3 is available (ENST00000380152.8): ENST00000380152.8:c.7397T>C MUST be fully validated prior to use in reports: select_variants=ENST00000380152.8:c.7397T>C",
            "A more recent version of the selected reference sequence ENST00000544455.1 is available (ENST00000544455.6): ENST00000544455.6:c.7397T>C MUST be fully validated prior to use in reports: select_variants=ENST00000544455.6:c.7397T>C",
            "ENST00000380152.3:c.7397T>C cannot be mapped directly to genome build GRCh38",
            "See alternative genomic loci or alternative genome builds for aligned genomic positions"
        ],
        "variant_exonic_positions": null
    },
    "ENST00000544455.1:c.7397T>C": {
        "alt_genomic_loci": [],
        "annotations": {
            "chromosome": "13",
            "db_xref": {
                "CCDS": null,
                "ensemblgene": "ENSG00000139618",
                "hgnc": "1101",
                "ncbigene": null,
                "select": "Ensembl"
            },
            "ensembl_select": true,
            "mane_plus_clinical": false,
            "mane_select": false,
            "map": "13q13.1",
            "note": "BRCA2 DNA repair associated",
            "refseq_select": false,
            "variant": "201"
        },
        "gene_ids": {
            "ccds_ids": [
                "CCDS9344"
            ],
            "ensembl_gene_id": "ENSG00000139618",
            "entrez_gene_id": "675",
            "hgnc_id": "HGNC:1101",
            "omim_id": [
                "600185"
            ],
            "ucsc_id": "uc001uub.2"
        },
        "gene_symbol": "BRCA2",
        "genome_context_intronic_sequence": "",
        "hgvs_lrg_transcript_variant": "",
        "hgvs_lrg_variant": "",
        "hgvs_predicted_protein_consequence": {
            "lrg_slr": "",
            "lrg_tlr": "",
            "slr": "ENSP00000439902.1:p.(V2466A)",
            "tlr": "ENSP00000439902.1:p.(Val2466Ala)"
        },
        "hgvs_refseqgene_variant": "",
        "hgvs_transcript_variant": "ENST00000544455.1:c.7397T>C",
        "primary_assembly_loci": {
            "grch37": {
                "hgvs_genomic_description": "NC_000013.10:g.32929387T>C",
                "vcf": {
                    "alt": "C",
                    "chr": "13",
                    "pos": "32929387",
                    "ref": "T"
                }
            },
            "grch38": {
                "hgvs_genomic_description": "NC_000013.11:g.32355250T>C",
                "vcf": {
                    "alt": "C",
                    "chr": "13",
                    "pos": "32355250",
                    "ref": "T"
                }
            },
            "hg19": {
                "hgvs_genomic_description": "NC_000013.10:g.32929387T>C",
                "vcf": {
                    "alt": "C",
                    "chr": "chr13",
                    "pos": "32929387",
                    "ref": "T"
                }
            },
            "hg38": {
                "hgvs_genomic_description": "NC_000013.11:g.32355250T>C",
                "vcf": {
                    "alt": "C",
                    "chr": "chr13",
                    "pos": "32355250",
                    "ref": "T"
                }
            }
        },
        "reference_sequence_records": "",
        "refseqgene_context_intronic_sequence": "",
        "selected_assembly": "GRCh38",
        "submitted_variant": "NC_000013.10:g.32929387T>C",
        "transcript_description": "BRCA2-201",
        "validation_warnings": [
            "A more recent version of the selected reference sequence ENST00000380152.3 is available (ENST00000380152.8): ENST00000380152.8:c.7397T>C MUST be fully validated prior to use in reports: select_variants=ENST00000380152.8:c.7397T>C",
            "A more recent version of the selected reference sequence ENST00000544455.1 is available (ENST00000544455.6): ENST00000544455.6:c.7397T>C MUST be fully validated prior to use in reports: select_variants=ENST00000544455.6:c.7397T>C",
            "ENST00000380152.3:c.7397T>C cannot be mapped directly to genome build GRCh38",
            "See alternative genomic loci or alternative genome builds for aligned genomic positions",
            "ENST00000544455.1:c.7397T>C cannot be mapped directly to genome build GRCh38"
        ],
        "variant_exonic_positions": null
    },
    "flag": "gene_variant",
    "metadata": {
        "variantvalidator_hgvs_version": "2.0.2.dev1+g6ecbf8e",
        "variantvalidator_version": "1.0.5.dev273+g7d58e7e.d20220617",
        "vvdb_version": "vvdb_2022_04",
        "vvseqrepo_db": "VV_SR_2022_02/master",
        "vvta_version": "vvta_2022_02"
    }
}
```

**Comment by sbenny1230** [comment]
I'm still trying to figure out what's causing it but just wanted to check if this is expected behaviour or if you any idea what's causing this?

**Comment by Peter-J-Freeman** [comment]
I'll take a look at this. Will be tomorrow. Will get back to you

**Comment by Peter-J-Freeman** [comment]
Hiya,

OK, yes and no r.e. the " is expected" question. 

Unlike RefSeq, Ensembl only align 1 version of the transcript to each genome, so you should get a waring if the wrong genome build is selected. 

So, for the transcript ENST00000380152, .3 only aligns to GRCh37 https://grch37.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000139618;r=13:32889611-32973347;t=ENST00000380152 and .8 to GRCh38 https://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000139618;r=13:32315508-32400268;t=ENST00000380152. 

So the question is, how have you have selected GRCh38 but returned a GRCh37 transcript. 

The answer is pretty simple to be honest. NC_000013.10:g.32929387T>C is part of genome build GRCh37, see here and look for NC_000013.10 https://github.com/openvar/variantValidator/blob/master/VariantValidator/modules/seq_data.py on line 41. So, what's happening is that the code is correctly identifying transcript ENST00000380152.3 and mapping to it. It then goes on to warn that 

```text
 more recent version of the selected reference sequence ENST00000380152.3 is available (ENST00000380152.8): ENST00000380152.8:c.7397T>C MUST be fully validated prior to use in reports: select_variants=ENST00000380152.8:c.7397T>C",
"ENST00000380152.3:c.7397T>C cannot be mapped directly to genome build GRCh38",
```

These warnings are correct and make entire sense in the context of RefSeq, but need rewording in the context of Ensembl reference sequences.

Perhaps warnings could be amended to the following for Ensembl

```
A more recent version of the selected reference sequence ENST00000380152.3 is available (ENST00000380152.8): ENST00000380152.8:c.7397T>C MUST be fully validated prior to use in reports: select_variants=ENST00000380152.8:c.7397T>C, genome_build=GRCh38",
```

```
"ENST00000380152.3:c.7397T>C cannot be mapped directly to genome build GRCh38", did you mean GRCh37?
```

and vice versa etc. Make sense???

**Comment by sbenny1230** [comment]
@Peter-J-Freeman just wondering how you would know if a particular transcript is part of the genome build or not? So is there a particular check that happens to tell if its part of the build or not so this message can be displayed `NC_000013.10 is not part of GRCh38`.

I assumed it would be any time this message appears `"ENST00000380152.3:c.7397T>C cannot be mapped directly to genome build GRCh38"` but then it wouldn't make sense to show two messages for the same issue

**Comment by Peter-J-Freeman** [comment]
Good question. I think perhaps some if statements e.g.

```
if (selected_assembly == GRCh38 or selected_assembly == hg38) and "cannot be mapped directly to genome build" not in warnings:
    base url = GRCh38

if (selected_assembly == GRCh37 or selected_assembly == hg19) and "cannot be mapped directly to genome build" not in warnings:
    base url = GRCh37
```

**Comment by Peter-J-Freeman** [comment]
This too. Are we happy to close?

**Comment by sbenny1230** [comment]
Yes, this is sorted now on vv_ensembl_dev_susmi
