### ISSUE TITLE
issue with docker containers

### ISSUE THREAD

**Issue by beboche** [openvar/variantValidator#95]
I experienced an issue with vv_docker:

On both my dev and demo machine, after about 24h, the vv rest api did not work anymore.
A docker ps showed the containers as working:

```
docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                            NAMES
1314abbc2202        rest_variantvalidator_restvv   "/bin/sh -c 'gunic..."   2 days ago          Up 26 hours         0.0.0.0:5000->5000/tcp, 0.0.0.0:8000->8000/tcp   rest_variantvalidator_restvv_1
32a0a66b1bbd        rest_variantvalidator_uta      "docker-entrypoint..."   2 days ago          Up 26 hours         0.0.0.0:5432->5432/tcp                           rest_variantvalidator_uta_1
af48633d820c        rest_variantvalidator_vdb      "docker-entrypoint..."   2 days ago          Up 26 hours         0.0.0.0:3306->3306/tcp, 33060/tcp                rest_variantvalidator_vdb_1
```

However, when I launched a vv query, I had a flask error:

```
Traceback (most recent call last):
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
restvv_1   |     rv = self.dispatch_request()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
restvv_1   |     return self.view_functions[rule.endpoint](**req.view_args)
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
restvv_1   |     resp = resource(*args, **kwargs)
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 89, in view
restvv_1   |     return self.dispatch_request(*args, **kwargs)
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
restvv_1   |     resp = meth(*args, **kwargs)
restvv_1   |   File "/app/rest_variantValidator/app.py", line 126, in get
restvv_1   |     mail.send(msg)
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/flask_mail.py", line 491, in send
restvv_1   |     with self.connect() as connection:
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/flask_mail.py", line 144, in __enter__
restvv_1   |     self.host = self.configure_host()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/flask_mail.py", line 158, in configure_host
restvv_1   |     host = smtplib.SMTP(self.mail.server, self.mail.port)
restvv_1   |   File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
restvv_1   |     (code, msg) = self.connect(host, port)
restvv_1   |   File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
restvv_1   |     self.sock = self._get_socket(host, port, self.timeout)
restvv_1   |   File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
restvv_1   |     self.source_address)
restvv_1   |   File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
restvv_1   |     raise err
restvv_1   |   File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
restvv_1   |     sock.connect(sa)
restvv_1   | ConnectionRefusedError: [Errno 111] Connection refused
```

The app could not connect anymore to either of the 2 databases. Killing (Ctrl-C) the process and starting again (docker-compose up) fixed the issue. This happened on 2 distinct machines.

**Comment by PeteCausey-Freeman** [comment]
Thanks for the bug report. 

This is an issue with the rest interface docker containers. The vv containers are in need of an update as well, but they are less commonly used.

Bug fixed with this commit. https://github.com/openvar/rest_variantValidator/pull/16

Recommend deleting the rest_vv container and re-building.
